# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxdefinition',
            options={'verbose_name_plural': 'Tax Definitions'},
        ),
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
