# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20180309_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='tax_definition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='accounting.TaxDefinition'),
            preserve_default=False,
        ),
    ]
