# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20180309_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorditem',
            name='tax',
        ),
        migrations.AddField(
            model_name='recorditem',
            name='tax',
            field=models.ManyToManyField(to='accounting.Tax'),
        ),
    ]
